// generated by cdktf get
// terraform-aws-modules/eks/aws//modules/self-managed-node-group
import { TerraformModule } from 'cdktf';
import { Construct } from 'constructs';
export interface EksSelfManagedNodeGroupOptions {
  /**
   * The AMI from which to launch the instance
   */
  readonly amiId?: string;
  /**
   * A list of one or more availability zones for the group. Used for EC2-Classic and default subnets when not specified with `subnet_ids` argument. Conflicts with `subnet_ids`
   */
  readonly availabilityZones?: string[];
  /**
   * Specify volumes to attach to the instance besides the volumes specified by the AMI
   * @default [object Object]
   */
  readonly blockDeviceMappings?: any;
  /**
   * Additional arguments passed to the bootstrap script. When `platform` = `bottlerocket`; these are additional [settings](https://github.com/bottlerocket-os/bottlerocket#settings) that are provided to the Bottlerocket user data
   */
  readonly bootstrapExtraArgs?: string;
  /**
   * Indicates whether capacity rebalance is enabled
   */
  readonly capacityRebalance?: boolean;
  /**
   * Targeting for EC2 capacity reservations
   */
  readonly capacityReservationSpecification?: any;
  /**
   * Base64 encoded CA of associated EKS cluster
   */
  readonly clusterAuthBase64?: string;
  /**
   * Endpoint of associated EKS cluster
   */
  readonly clusterEndpoint?: string;
  /**
   * The IP family used to assign Kubernetes pod and service addresses. Valid values are `ipv4` (default) and `ipv6`
   */
  readonly clusterIpFamily?: string;
  /**
   * Name of associated EKS cluster
   */
  readonly clusterName?: string;
  /**
   * The ID of the EKS cluster primary security group to associate with the instance(s). This is the security group that is automatically created by the EKS service
   */
  readonly clusterPrimarySecurityGroupId?: string;
  /**
   * Cluster control plane security group ID
   */
  readonly clusterSecurityGroupId?: string;
  /**
   * Kubernetes cluster version - used to lookup default AMI ID if one is not provided
   */
  readonly clusterVersion?: string;
  /**
   * The CPU options for the instance
   * The property type contains a map, they have special handling, please see {@link cdk.tf/module-map-inputs the docs}
   */
  readonly cpuOptions?: { [key: string]: string };
  /**
   * Determines whether to create self managed node group or not
   * @default true
   */
  readonly create?: boolean;
  /**
   * Determines whether an IAM instance profile is created or to use an existing IAM instance profile
   * @default true
   */
  readonly createIamInstanceProfile?: boolean;
  /**
   * Determines whether to create launch template or not
   * @default true
   */
  readonly createLaunchTemplate?: boolean;
  /**
   * Determines whether to create autoscaling group schedule or not
   * @default true
   */
  readonly createSchedule?: boolean;
  /**
   * Determines whether to create a security group
   * @default true
   */
  readonly createSecurityGroup?: boolean;
  /**
   * Customize the credit specification of the instance
   * The property type contains a map, they have special handling, please see {@link cdk.tf/module-map-inputs the docs}
   */
  readonly creditSpecification?: { [key: string]: string };
  /**
   * The amount of time, in seconds, after a scaling activity completes before another scaling activity can start
   */
  readonly defaultCooldown?: number;
  /**
   * Delete timeout to wait for destroying autoscaling group
   */
  readonly deleteTimeout?: string;
  /**
   * The number of Amazon EC2 instances that should be running in the autoscaling group
   * @default 1
   */
  readonly desiredSize?: number;
  /**
   * If true, enables EC2 instance termination protection
   */
  readonly disableApiTermination?: boolean;
  /**
   * If true, the launched EC2 instance will be EBS-optimized
   */
  readonly ebsOptimized?: boolean;
  /**
   * The elastic GPU to attach to the instance
   * The property type contains a map, they have special handling, please see {@link cdk.tf/module-map-inputs the docs}
   */
  readonly elasticGpuSpecifications?: { [key: string]: string };
  /**
   * Configuration block containing an Elastic Inference Accelerator to attach to the instance
   * The property type contains a map, they have special handling, please see {@link cdk.tf/module-map-inputs the docs}
   */
  readonly elasticInferenceAccelerator?: { [key: string]: string };
  /**
   * Enables/disables detailed monitoring
   * @default true
   */
  readonly enableMonitoring?: boolean;
  /**
   * A list of metrics to collect. The allowed values are `GroupDesiredCapacity`, `GroupInServiceCapacity`, `GroupPendingCapacity`, `GroupMinSize`, `GroupMaxSize`, `GroupInServiceInstances`, `GroupPendingInstances`, `GroupStandbyInstances`, `GroupStandbyCapacity`, `GroupTerminatingCapacity`, `GroupTerminatingInstances`, `GroupTotalCapacity`, `GroupTotalInstances`
   */
  readonly enabledMetrics?: string[];
  /**
   * Enable Nitro Enclaves on launched instances
   * The property type contains a map, they have special handling, please see {@link cdk.tf/module-map-inputs the docs}
   */
  readonly enclaveOptions?: { [key: string]: string };
  /**
   * Allows deleting the Auto Scaling Group without waiting for all instances in the pool to terminate. You can force an Auto Scaling Group to delete even if it's in the process of scaling a resource. Normally, Terraform drains all the instances before deleting the group. This bypasses that behavior and potentially leaves resources dangling
   */
  readonly forceDelete?: boolean;
  /**
   * Time (in seconds) after instance comes into service before checking health
   */
  readonly healthCheckGracePeriod?: number;
  /**
   * `EC2` or `ELB`. Controls how health checking is done
   */
  readonly healthCheckType?: string;
  /**
   * The hibernation options for the instance
   * The property type contains a map, they have special handling, please see {@link cdk.tf/module-map-inputs the docs}
   */
  readonly hibernationOptions?: { [key: string]: string };
  /**
   * Amazon Resource Name (ARN) of an existing IAM instance profile that provides permissions for the node group. Required if `create_iam_instance_profile` = `false`
   */
  readonly iamInstanceProfileArn?: string;
  /**
   * Additional policies to be added to the IAM role
   * @default 
   */
  readonly iamRoleAdditionalPolicies?: string[];
  /**
   * Whether to attach the `AmazonEKS_CNI_Policy`/`AmazonEKS_CNI_IPv6_Policy` IAM policy to the IAM IAM role. WARNING: If set `false` the permissions must be assigned to the `aws-node` DaemonSet pods via another method or nodes will not be able to join the cluster
   * @default true
   */
  readonly iamRoleAttachCniPolicy?: boolean;
  /**
   * Description of the role
   */
  readonly iamRoleDescription?: string;
  /**
   * Name to use on IAM role created
   */
  readonly iamRoleName?: string;
  /**
   * IAM role path
   */
  readonly iamRolePath?: string;
  /**
   * ARN of the policy that is used to set the permissions boundary for the IAM role
   */
  readonly iamRolePermissionsBoundary?: string;
  /**
   * A map of additional tags to add to the IAM role created
   * @default [object Object]
   * The property type contains a map, they have special handling, please see {@link cdk.tf/module-map-inputs the docs}
   */
  readonly iamRoleTags?: { [key: string]: string };
  /**
   * Determines whether cluster IAM role name (`iam_role_name`) is used as a prefix
   * @default true
   */
  readonly iamRoleUseNamePrefix?: boolean;
  /**
   * One or more Lifecycle Hooks to attach to the Auto Scaling Group before instances are launched. The syntax is exactly the same as the separate `aws_autoscaling_lifecycle_hook` resource, without the `autoscaling_group_name` attribute. Please note that this will only work when creating a new Auto Scaling Group. For all other use-cases, please use `aws_autoscaling_lifecycle_hook` resource
   * @default 
   * The property type contains a map, they have special handling, please see {@link cdk.tf/module-map-inputs the docs}
   */
  readonly initialLifecycleHooks?: { [key: string]: string }[];
  /**
   * Shutdown behavior for the instance. Can be `stop` or `terminate`. (Default: `stop`)
   */
  readonly instanceInitiatedShutdownBehavior?: string;
  /**
   * The market (purchasing) option for the instance
   */
  readonly instanceMarketOptions?: any;
  /**
   * If this block is configured, start an Instance Refresh when this Auto Scaling Group is updated
   */
  readonly instanceRefresh?: any;
  /**
   * The type of the instance to launch
   */
  readonly instanceType?: string;
  /**
   * The kernel ID
   */
  readonly kernelId?: string;
  /**
   * The key name that should be used for the instance
   */
  readonly keyName?: string;
  /**
   * Default Version of the launch template
   */
  readonly launchTemplateDefaultVersion?: string;
  /**
   * Description of the launch template
   */
  readonly launchTemplateDescription?: string;
  /**
   * Launch template name - either to be created (`var.create_launch_template` = `true`) or existing (`var.create_launch_template` = `false`)
   */
  readonly launchTemplateName?: string;
  /**
   * A map of additional tags to add to the tag_specifications of launch template created
   * @default [object Object]
   * The property type contains a map, they have special handling, please see {@link cdk.tf/module-map-inputs the docs}
   */
  readonly launchTemplateTags?: { [key: string]: string };
  /**
   * Determines whether to use `launch_template_name` as is or create a unique name beginning with the `launch_template_name` as the prefix
   * @default true
   */
  readonly launchTemplateUseNamePrefix?: boolean;
  /**
   * Launch template version. Can be version number, `$Latest`, or `$Default`
   */
  readonly launchTemplateVersion?: string;
  /**
   * A list of license specifications to associate with
   * The property type contains a map, they have special handling, please see {@link cdk.tf/module-map-inputs the docs}
   */
  readonly licenseSpecifications?: { [key: string]: string };
  /**
   * The maximum amount of time, in seconds, that an instance can be in service, values must be either equal to 0 or between 604800 and 31536000 seconds
   */
  readonly maxInstanceLifetime?: number;
  /**
   * The maximum size of the autoscaling group
   * @default 3
   */
  readonly maxSize?: number;
  /**
   * Customize the metadata options for the instance
   * @default [object Object]
   * The property type contains a map, they have special handling, please see {@link cdk.tf/module-map-inputs the docs}
   */
  readonly metadataOptions?: { [key: string]: string };
  /**
   * The granularity to associate with the metrics to collect. The only valid value is `1Minute`
   */
  readonly metricsGranularity?: string;
  /**
   * Setting this causes Terraform to wait for this number of instances to show up healthy in the ELB only on creation. Updates will not wait on ELB instance number changes
   */
  readonly minElbCapacity?: number;
  /**
   * The minimum size of the autoscaling group
   */
  readonly minSize?: number;
  /**
   * Configuration block containing settings to define launch targets for Auto Scaling groups
   */
  readonly mixedInstancesPolicy?: any;
  /**
   * Name of the Self managed Node Group
   */
  readonly name?: string;
  /**
   * Customize network interfaces to be attached at instance boot time
   * @default 
   */
  readonly networkInterfaces?: any[];
  /**
   * The placement of the instance
   * The property type contains a map, they have special handling, please see {@link cdk.tf/module-map-inputs the docs}
   */
  readonly placement?: { [key: string]: string };
  /**
   * The name of the placement group into which you'll launch your instances, if any
   */
  readonly placementGroup?: string;
  /**
   * Identifies if the OS platform is `bottlerocket`, `linux`, or `windows` based
   * @default linux
   */
  readonly platform?: string;
  /**
   * User data that is appended to the user data script after of the EKS bootstrap script. Not used when `platform` = `bottlerocket`
   */
  readonly postBootstrapUserData?: string;
  /**
   * User data that is injected into the user data script ahead of the EKS bootstrap script. Not used when `platform` = `bottlerocket`
   */
  readonly preBootstrapUserData?: string;
  /**
   * Allows setting instance protection. The autoscaling group will not select instances with this setting for termination during scale in events.
   */
  readonly protectFromScaleIn?: boolean;
  /**
   * The ID of the ram disk
   */
  readonly ramDiskId?: string;
  /**
   * Map of autoscaling group schedule to create
   * @default [object Object]
   * The property type contains a map, they have special handling, please see {@link cdk.tf/module-map-inputs the docs}
   */
  readonly schedules?: { [key: string]: any };
  /**
   * Description for the security group created
   * @default EKS self-managed node group security group
   */
  readonly securityGroupDescription?: string;
  /**
   * Name to use on security group created
   */
  readonly securityGroupName?: string;
  /**
   * List of security group rules to add to the security group created
   * @default [object Object]
   */
  readonly securityGroupRules?: any;
  /**
   * A map of additional tags to add to the security group created
   * @default [object Object]
   * The property type contains a map, they have special handling, please see {@link cdk.tf/module-map-inputs the docs}
   */
  readonly securityGroupTags?: { [key: string]: string };
  /**
   * Determines whether the security group name (`security_group_name`) is used as a prefix
   * @default true
   */
  readonly securityGroupUseNamePrefix?: string;
  /**
   * The ARN of the service-linked role that the ASG will use to call other AWS services
   */
  readonly serviceLinkedRoleArn?: string;
  /**
   * A list of subnet IDs to launch resources in. Subnets automatically determine which availability zones the group will reside. Conflicts with `availability_zones`
   */
  readonly subnetIds?: string[];
  /**
   * A list of processes to suspend for the Auto Scaling Group. The allowed values are `Launch`, `Terminate`, `HealthCheck`, `ReplaceUnhealthy`, `AZRebalance`, `AlarmNotification`, `ScheduledActions`, `AddToLoadBalancer`. Note that if you suspend either the `Launch` or `Terminate` process types, it can prevent your Auto Scaling Group from functioning properly
   */
  readonly suspendedProcesses?: string[];
  /**
   * A map of tags to add to all resources
   * @default [object Object]
   * The property type contains a map, they have special handling, please see {@link cdk.tf/module-map-inputs the docs}
   */
  readonly tags?: { [key: string]: string };
  /**
   * A set of `aws_alb_target_group` ARNs, for use with Application or Network Load Balancing
   * @default 
   */
  readonly targetGroupArns?: string[];
  /**
   * A list of policies to decide how the instances in the Auto Scaling Group should be terminated. The allowed values are `OldestInstance`, `NewestInstance`, `OldestLaunchConfiguration`, `ClosestToNextInstanceHour`, `OldestLaunchTemplate`, `AllocationStrategy`, `Default`
   */
  readonly terminationPolicies?: string[];
  /**
   * Whether to update Default Version each update. Conflicts with `launch_template_default_version`
   * @default true
   */
  readonly updateLaunchTemplateDefaultVersion?: boolean;
  /**
   * Enables/disables the use of provider default tags in the tag_specifications of the Auto Scaling group
   */
  readonly useDefaultTags?: boolean;
  /**
   * Determines whether to use a mixed instances policy in the autoscaling group or not
   */
  readonly useMixedInstancesPolicy?: boolean;
  /**
   * Determines whether to use `name` as is or create a unique name beginning with the `name` as the prefix
   * @default true
   */
  readonly useNamePrefix?: boolean;
  /**
   * Path to a local, custom user data template file to use when rendering user data
   */
  readonly userDataTemplatePath?: string;
  /**
   * ID of the VPC where the security group/nodes will be provisioned
   */
  readonly vpcId?: string;
  /**
   * A list of security group IDs to associate
   * @default 
   */
  readonly vpcSecurityGroupIds?: string[];
  /**
   * A maximum duration that Terraform should wait for ASG instances to be healthy before timing out. (See also Waiting for Capacity below.) Setting this to '0' causes Terraform to skip all Capacity Waiting behavior.
   */
  readonly waitForCapacityTimeout?: string;
  /**
   * Setting this will cause Terraform to wait for exactly this number of healthy instances in all attached load balancers on both create and update operations. Takes precedence over `min_elb_capacity` behavior.
   */
  readonly waitForElbCapacity?: number;
  /**
   * If this block is configured, add a Warm Pool to the specified Auto Scaling group
   */
  readonly warmPool?: any;
}
export class EksSelfManagedNodeGroup extends TerraformModule {
  private readonly inputs: { [name: string]: any } = { }
  public constructor(scope: Construct, id: string, options: EksSelfManagedNodeGroupOptions = {}) {
    super(scope, id, {
      source: 'terraform-aws-modules/eks/aws//modules/self-managed-node-group',
      version: '18.20.5',
    });
    this.amiId = options.amiId;
    this.availabilityZones = options.availabilityZones;
    this.blockDeviceMappings = options.blockDeviceMappings;
    this.bootstrapExtraArgs = options.bootstrapExtraArgs;
    this.capacityRebalance = options.capacityRebalance;
    this.capacityReservationSpecification = options.capacityReservationSpecification;
    this.clusterAuthBase64 = options.clusterAuthBase64;
    this.clusterEndpoint = options.clusterEndpoint;
    this.clusterIpFamily = options.clusterIpFamily;
    this.clusterName = options.clusterName;
    this.clusterPrimarySecurityGroupId = options.clusterPrimarySecurityGroupId;
    this.clusterSecurityGroupId = options.clusterSecurityGroupId;
    this.clusterVersion = options.clusterVersion;
    this.cpuOptions = options.cpuOptions;
    this.create = options.create;
    this.createIamInstanceProfile = options.createIamInstanceProfile;
    this.createLaunchTemplate = options.createLaunchTemplate;
    this.createSchedule = options.createSchedule;
    this.createSecurityGroup = options.createSecurityGroup;
    this.creditSpecification = options.creditSpecification;
    this.defaultCooldown = options.defaultCooldown;
    this.deleteTimeout = options.deleteTimeout;
    this.desiredSize = options.desiredSize;
    this.disableApiTermination = options.disableApiTermination;
    this.ebsOptimized = options.ebsOptimized;
    this.elasticGpuSpecifications = options.elasticGpuSpecifications;
    this.elasticInferenceAccelerator = options.elasticInferenceAccelerator;
    this.enableMonitoring = options.enableMonitoring;
    this.enabledMetrics = options.enabledMetrics;
    this.enclaveOptions = options.enclaveOptions;
    this.forceDelete = options.forceDelete;
    this.healthCheckGracePeriod = options.healthCheckGracePeriod;
    this.healthCheckType = options.healthCheckType;
    this.hibernationOptions = options.hibernationOptions;
    this.iamInstanceProfileArn = options.iamInstanceProfileArn;
    this.iamRoleAdditionalPolicies = options.iamRoleAdditionalPolicies;
    this.iamRoleAttachCniPolicy = options.iamRoleAttachCniPolicy;
    this.iamRoleDescription = options.iamRoleDescription;
    this.iamRoleName = options.iamRoleName;
    this.iamRolePath = options.iamRolePath;
    this.iamRolePermissionsBoundary = options.iamRolePermissionsBoundary;
    this.iamRoleTags = options.iamRoleTags;
    this.iamRoleUseNamePrefix = options.iamRoleUseNamePrefix;
    this.initialLifecycleHooks = options.initialLifecycleHooks;
    this.instanceInitiatedShutdownBehavior = options.instanceInitiatedShutdownBehavior;
    this.instanceMarketOptions = options.instanceMarketOptions;
    this.instanceRefresh = options.instanceRefresh;
    this.instanceType = options.instanceType;
    this.kernelId = options.kernelId;
    this.keyName = options.keyName;
    this.launchTemplateDefaultVersion = options.launchTemplateDefaultVersion;
    this.launchTemplateDescription = options.launchTemplateDescription;
    this.launchTemplateName = options.launchTemplateName;
    this.launchTemplateTags = options.launchTemplateTags;
    this.launchTemplateUseNamePrefix = options.launchTemplateUseNamePrefix;
    this.launchTemplateVersion = options.launchTemplateVersion;
    this.licenseSpecifications = options.licenseSpecifications;
    this.maxInstanceLifetime = options.maxInstanceLifetime;
    this.maxSize = options.maxSize;
    this.metadataOptions = options.metadataOptions;
    this.metricsGranularity = options.metricsGranularity;
    this.minElbCapacity = options.minElbCapacity;
    this.minSize = options.minSize;
    this.mixedInstancesPolicy = options.mixedInstancesPolicy;
    this.name = options.name;
    this.networkInterfaces = options.networkInterfaces;
    this.placement = options.placement;
    this.placementGroup = options.placementGroup;
    this.platform = options.platform;
    this.postBootstrapUserData = options.postBootstrapUserData;
    this.preBootstrapUserData = options.preBootstrapUserData;
    this.protectFromScaleIn = options.protectFromScaleIn;
    this.ramDiskId = options.ramDiskId;
    this.schedules = options.schedules;
    this.securityGroupDescription = options.securityGroupDescription;
    this.securityGroupName = options.securityGroupName;
    this.securityGroupRules = options.securityGroupRules;
    this.securityGroupTags = options.securityGroupTags;
    this.securityGroupUseNamePrefix = options.securityGroupUseNamePrefix;
    this.serviceLinkedRoleArn = options.serviceLinkedRoleArn;
    this.subnetIds = options.subnetIds;
    this.suspendedProcesses = options.suspendedProcesses;
    this.tags = options.tags;
    this.targetGroupArns = options.targetGroupArns;
    this.terminationPolicies = options.terminationPolicies;
    this.updateLaunchTemplateDefaultVersion = options.updateLaunchTemplateDefaultVersion;
    this.useDefaultTags = options.useDefaultTags;
    this.useMixedInstancesPolicy = options.useMixedInstancesPolicy;
    this.useNamePrefix = options.useNamePrefix;
    this.userDataTemplatePath = options.userDataTemplatePath;
    this.vpcId = options.vpcId;
    this.vpcSecurityGroupIds = options.vpcSecurityGroupIds;
    this.waitForCapacityTimeout = options.waitForCapacityTimeout;
    this.waitForElbCapacity = options.waitForElbCapacity;
    this.warmPool = options.warmPool;
  }
  public get amiId(): string | undefined {
    return this.inputs['ami_id'] as string | undefined;
  }
  public set amiId(value: string | undefined) {
    this.inputs['ami_id'] = value;
  }
  public get availabilityZones(): string[] | undefined {
    return this.inputs['availability_zones'] as string[] | undefined;
  }
  public set availabilityZones(value: string[] | undefined) {
    this.inputs['availability_zones'] = value;
  }
  public get blockDeviceMappings(): any | undefined {
    return this.inputs['block_device_mappings'] as any | undefined;
  }
  public set blockDeviceMappings(value: any | undefined) {
    this.inputs['block_device_mappings'] = value;
  }
  public get bootstrapExtraArgs(): string | undefined {
    return this.inputs['bootstrap_extra_args'] as string | undefined;
  }
  public set bootstrapExtraArgs(value: string | undefined) {
    this.inputs['bootstrap_extra_args'] = value;
  }
  public get capacityRebalance(): boolean | undefined {
    return this.inputs['capacity_rebalance'] as boolean | undefined;
  }
  public set capacityRebalance(value: boolean | undefined) {
    this.inputs['capacity_rebalance'] = value;
  }
  public get capacityReservationSpecification(): any | undefined {
    return this.inputs['capacity_reservation_specification'] as any | undefined;
  }
  public set capacityReservationSpecification(value: any | undefined) {
    this.inputs['capacity_reservation_specification'] = value;
  }
  public get clusterAuthBase64(): string | undefined {
    return this.inputs['cluster_auth_base64'] as string | undefined;
  }
  public set clusterAuthBase64(value: string | undefined) {
    this.inputs['cluster_auth_base64'] = value;
  }
  public get clusterEndpoint(): string | undefined {
    return this.inputs['cluster_endpoint'] as string | undefined;
  }
  public set clusterEndpoint(value: string | undefined) {
    this.inputs['cluster_endpoint'] = value;
  }
  public get clusterIpFamily(): string | undefined {
    return this.inputs['cluster_ip_family'] as string | undefined;
  }
  public set clusterIpFamily(value: string | undefined) {
    this.inputs['cluster_ip_family'] = value;
  }
  public get clusterName(): string | undefined {
    return this.inputs['cluster_name'] as string | undefined;
  }
  public set clusterName(value: string | undefined) {
    this.inputs['cluster_name'] = value;
  }
  public get clusterPrimarySecurityGroupId(): string | undefined {
    return this.inputs['cluster_primary_security_group_id'] as string | undefined;
  }
  public set clusterPrimarySecurityGroupId(value: string | undefined) {
    this.inputs['cluster_primary_security_group_id'] = value;
  }
  public get clusterSecurityGroupId(): string | undefined {
    return this.inputs['cluster_security_group_id'] as string | undefined;
  }
  public set clusterSecurityGroupId(value: string | undefined) {
    this.inputs['cluster_security_group_id'] = value;
  }
  public get clusterVersion(): string | undefined {
    return this.inputs['cluster_version'] as string | undefined;
  }
  public set clusterVersion(value: string | undefined) {
    this.inputs['cluster_version'] = value;
  }
  public get cpuOptions(): { [key: string]: string } | undefined {
    return this.inputs['cpu_options'] as { [key: string]: string } | undefined;
  }
  public set cpuOptions(value: { [key: string]: string } | undefined) {
    this.inputs['cpu_options'] = value;
  }
  public get create(): boolean | undefined {
    return this.inputs['create'] as boolean | undefined;
  }
  public set create(value: boolean | undefined) {
    this.inputs['create'] = value;
  }
  public get createIamInstanceProfile(): boolean | undefined {
    return this.inputs['create_iam_instance_profile'] as boolean | undefined;
  }
  public set createIamInstanceProfile(value: boolean | undefined) {
    this.inputs['create_iam_instance_profile'] = value;
  }
  public get createLaunchTemplate(): boolean | undefined {
    return this.inputs['create_launch_template'] as boolean | undefined;
  }
  public set createLaunchTemplate(value: boolean | undefined) {
    this.inputs['create_launch_template'] = value;
  }
  public get createSchedule(): boolean | undefined {
    return this.inputs['create_schedule'] as boolean | undefined;
  }
  public set createSchedule(value: boolean | undefined) {
    this.inputs['create_schedule'] = value;
  }
  public get createSecurityGroup(): boolean | undefined {
    return this.inputs['create_security_group'] as boolean | undefined;
  }
  public set createSecurityGroup(value: boolean | undefined) {
    this.inputs['create_security_group'] = value;
  }
  public get creditSpecification(): { [key: string]: string } | undefined {
    return this.inputs['credit_specification'] as { [key: string]: string } | undefined;
  }
  public set creditSpecification(value: { [key: string]: string } | undefined) {
    this.inputs['credit_specification'] = value;
  }
  public get defaultCooldown(): number | undefined {
    return this.inputs['default_cooldown'] as number | undefined;
  }
  public set defaultCooldown(value: number | undefined) {
    this.inputs['default_cooldown'] = value;
  }
  public get deleteTimeout(): string | undefined {
    return this.inputs['delete_timeout'] as string | undefined;
  }
  public set deleteTimeout(value: string | undefined) {
    this.inputs['delete_timeout'] = value;
  }
  public get desiredSize(): number | undefined {
    return this.inputs['desired_size'] as number | undefined;
  }
  public set desiredSize(value: number | undefined) {
    this.inputs['desired_size'] = value;
  }
  public get disableApiTermination(): boolean | undefined {
    return this.inputs['disable_api_termination'] as boolean | undefined;
  }
  public set disableApiTermination(value: boolean | undefined) {
    this.inputs['disable_api_termination'] = value;
  }
  public get ebsOptimized(): boolean | undefined {
    return this.inputs['ebs_optimized'] as boolean | undefined;
  }
  public set ebsOptimized(value: boolean | undefined) {
    this.inputs['ebs_optimized'] = value;
  }
  public get elasticGpuSpecifications(): { [key: string]: string } | undefined {
    return this.inputs['elastic_gpu_specifications'] as { [key: string]: string } | undefined;
  }
  public set elasticGpuSpecifications(value: { [key: string]: string } | undefined) {
    this.inputs['elastic_gpu_specifications'] = value;
  }
  public get elasticInferenceAccelerator(): { [key: string]: string } | undefined {
    return this.inputs['elastic_inference_accelerator'] as { [key: string]: string } | undefined;
  }
  public set elasticInferenceAccelerator(value: { [key: string]: string } | undefined) {
    this.inputs['elastic_inference_accelerator'] = value;
  }
  public get enableMonitoring(): boolean | undefined {
    return this.inputs['enable_monitoring'] as boolean | undefined;
  }
  public set enableMonitoring(value: boolean | undefined) {
    this.inputs['enable_monitoring'] = value;
  }
  public get enabledMetrics(): string[] | undefined {
    return this.inputs['enabled_metrics'] as string[] | undefined;
  }
  public set enabledMetrics(value: string[] | undefined) {
    this.inputs['enabled_metrics'] = value;
  }
  public get enclaveOptions(): { [key: string]: string } | undefined {
    return this.inputs['enclave_options'] as { [key: string]: string } | undefined;
  }
  public set enclaveOptions(value: { [key: string]: string } | undefined) {
    this.inputs['enclave_options'] = value;
  }
  public get forceDelete(): boolean | undefined {
    return this.inputs['force_delete'] as boolean | undefined;
  }
  public set forceDelete(value: boolean | undefined) {
    this.inputs['force_delete'] = value;
  }
  public get healthCheckGracePeriod(): number | undefined {
    return this.inputs['health_check_grace_period'] as number | undefined;
  }
  public set healthCheckGracePeriod(value: number | undefined) {
    this.inputs['health_check_grace_period'] = value;
  }
  public get healthCheckType(): string | undefined {
    return this.inputs['health_check_type'] as string | undefined;
  }
  public set healthCheckType(value: string | undefined) {
    this.inputs['health_check_type'] = value;
  }
  public get hibernationOptions(): { [key: string]: string } | undefined {
    return this.inputs['hibernation_options'] as { [key: string]: string } | undefined;
  }
  public set hibernationOptions(value: { [key: string]: string } | undefined) {
    this.inputs['hibernation_options'] = value;
  }
  public get iamInstanceProfileArn(): string | undefined {
    return this.inputs['iam_instance_profile_arn'] as string | undefined;
  }
  public set iamInstanceProfileArn(value: string | undefined) {
    this.inputs['iam_instance_profile_arn'] = value;
  }
  public get iamRoleAdditionalPolicies(): string[] | undefined {
    return this.inputs['iam_role_additional_policies'] as string[] | undefined;
  }
  public set iamRoleAdditionalPolicies(value: string[] | undefined) {
    this.inputs['iam_role_additional_policies'] = value;
  }
  public get iamRoleAttachCniPolicy(): boolean | undefined {
    return this.inputs['iam_role_attach_cni_policy'] as boolean | undefined;
  }
  public set iamRoleAttachCniPolicy(value: boolean | undefined) {
    this.inputs['iam_role_attach_cni_policy'] = value;
  }
  public get iamRoleDescription(): string | undefined {
    return this.inputs['iam_role_description'] as string | undefined;
  }
  public set iamRoleDescription(value: string | undefined) {
    this.inputs['iam_role_description'] = value;
  }
  public get iamRoleName(): string | undefined {
    return this.inputs['iam_role_name'] as string | undefined;
  }
  public set iamRoleName(value: string | undefined) {
    this.inputs['iam_role_name'] = value;
  }
  public get iamRolePath(): string | undefined {
    return this.inputs['iam_role_path'] as string | undefined;
  }
  public set iamRolePath(value: string | undefined) {
    this.inputs['iam_role_path'] = value;
  }
  public get iamRolePermissionsBoundary(): string | undefined {
    return this.inputs['iam_role_permissions_boundary'] as string | undefined;
  }
  public set iamRolePermissionsBoundary(value: string | undefined) {
    this.inputs['iam_role_permissions_boundary'] = value;
  }
  public get iamRoleTags(): { [key: string]: string } | undefined {
    return this.inputs['iam_role_tags'] as { [key: string]: string } | undefined;
  }
  public set iamRoleTags(value: { [key: string]: string } | undefined) {
    this.inputs['iam_role_tags'] = value;
  }
  public get iamRoleUseNamePrefix(): boolean | undefined {
    return this.inputs['iam_role_use_name_prefix'] as boolean | undefined;
  }
  public set iamRoleUseNamePrefix(value: boolean | undefined) {
    this.inputs['iam_role_use_name_prefix'] = value;
  }
  public get initialLifecycleHooks(): { [key: string]: string }[] | undefined {
    return this.inputs['initial_lifecycle_hooks'] as { [key: string]: string }[] | undefined;
  }
  public set initialLifecycleHooks(value: { [key: string]: string }[] | undefined) {
    this.inputs['initial_lifecycle_hooks'] = value;
  }
  public get instanceInitiatedShutdownBehavior(): string | undefined {
    return this.inputs['instance_initiated_shutdown_behavior'] as string | undefined;
  }
  public set instanceInitiatedShutdownBehavior(value: string | undefined) {
    this.inputs['instance_initiated_shutdown_behavior'] = value;
  }
  public get instanceMarketOptions(): any | undefined {
    return this.inputs['instance_market_options'] as any | undefined;
  }
  public set instanceMarketOptions(value: any | undefined) {
    this.inputs['instance_market_options'] = value;
  }
  public get instanceRefresh(): any | undefined {
    return this.inputs['instance_refresh'] as any | undefined;
  }
  public set instanceRefresh(value: any | undefined) {
    this.inputs['instance_refresh'] = value;
  }
  public get instanceType(): string | undefined {
    return this.inputs['instance_type'] as string | undefined;
  }
  public set instanceType(value: string | undefined) {
    this.inputs['instance_type'] = value;
  }
  public get kernelId(): string | undefined {
    return this.inputs['kernel_id'] as string | undefined;
  }
  public set kernelId(value: string | undefined) {
    this.inputs['kernel_id'] = value;
  }
  public get keyName(): string | undefined {
    return this.inputs['key_name'] as string | undefined;
  }
  public set keyName(value: string | undefined) {
    this.inputs['key_name'] = value;
  }
  public get launchTemplateDefaultVersion(): string | undefined {
    return this.inputs['launch_template_default_version'] as string | undefined;
  }
  public set launchTemplateDefaultVersion(value: string | undefined) {
    this.inputs['launch_template_default_version'] = value;
  }
  public get launchTemplateDescription(): string | undefined {
    return this.inputs['launch_template_description'] as string | undefined;
  }
  public set launchTemplateDescription(value: string | undefined) {
    this.inputs['launch_template_description'] = value;
  }
  public get launchTemplateName(): string | undefined {
    return this.inputs['launch_template_name'] as string | undefined;
  }
  public set launchTemplateName(value: string | undefined) {
    this.inputs['launch_template_name'] = value;
  }
  public get launchTemplateTags(): { [key: string]: string } | undefined {
    return this.inputs['launch_template_tags'] as { [key: string]: string } | undefined;
  }
  public set launchTemplateTags(value: { [key: string]: string } | undefined) {
    this.inputs['launch_template_tags'] = value;
  }
  public get launchTemplateUseNamePrefix(): boolean | undefined {
    return this.inputs['launch_template_use_name_prefix'] as boolean | undefined;
  }
  public set launchTemplateUseNamePrefix(value: boolean | undefined) {
    this.inputs['launch_template_use_name_prefix'] = value;
  }
  public get launchTemplateVersion(): string | undefined {
    return this.inputs['launch_template_version'] as string | undefined;
  }
  public set launchTemplateVersion(value: string | undefined) {
    this.inputs['launch_template_version'] = value;
  }
  public get licenseSpecifications(): { [key: string]: string } | undefined {
    return this.inputs['license_specifications'] as { [key: string]: string } | undefined;
  }
  public set licenseSpecifications(value: { [key: string]: string } | undefined) {
    this.inputs['license_specifications'] = value;
  }
  public get maxInstanceLifetime(): number | undefined {
    return this.inputs['max_instance_lifetime'] as number | undefined;
  }
  public set maxInstanceLifetime(value: number | undefined) {
    this.inputs['max_instance_lifetime'] = value;
  }
  public get maxSize(): number | undefined {
    return this.inputs['max_size'] as number | undefined;
  }
  public set maxSize(value: number | undefined) {
    this.inputs['max_size'] = value;
  }
  public get metadataOptions(): { [key: string]: string } | undefined {
    return this.inputs['metadata_options'] as { [key: string]: string } | undefined;
  }
  public set metadataOptions(value: { [key: string]: string } | undefined) {
    this.inputs['metadata_options'] = value;
  }
  public get metricsGranularity(): string | undefined {
    return this.inputs['metrics_granularity'] as string | undefined;
  }
  public set metricsGranularity(value: string | undefined) {
    this.inputs['metrics_granularity'] = value;
  }
  public get minElbCapacity(): number | undefined {
    return this.inputs['min_elb_capacity'] as number | undefined;
  }
  public set minElbCapacity(value: number | undefined) {
    this.inputs['min_elb_capacity'] = value;
  }
  public get minSize(): number | undefined {
    return this.inputs['min_size'] as number | undefined;
  }
  public set minSize(value: number | undefined) {
    this.inputs['min_size'] = value;
  }
  public get mixedInstancesPolicy(): any | undefined {
    return this.inputs['mixed_instances_policy'] as any | undefined;
  }
  public set mixedInstancesPolicy(value: any | undefined) {
    this.inputs['mixed_instances_policy'] = value;
  }
  public get name(): string | undefined {
    return this.inputs['name'] as string | undefined;
  }
  public set name(value: string | undefined) {
    this.inputs['name'] = value;
  }
  public get networkInterfaces(): any[] | undefined {
    return this.inputs['network_interfaces'] as any[] | undefined;
  }
  public set networkInterfaces(value: any[] | undefined) {
    this.inputs['network_interfaces'] = value;
  }
  public get placement(): { [key: string]: string } | undefined {
    return this.inputs['placement'] as { [key: string]: string } | undefined;
  }
  public set placement(value: { [key: string]: string } | undefined) {
    this.inputs['placement'] = value;
  }
  public get placementGroup(): string | undefined {
    return this.inputs['placement_group'] as string | undefined;
  }
  public set placementGroup(value: string | undefined) {
    this.inputs['placement_group'] = value;
  }
  public get platform(): string | undefined {
    return this.inputs['platform'] as string | undefined;
  }
  public set platform(value: string | undefined) {
    this.inputs['platform'] = value;
  }
  public get postBootstrapUserData(): string | undefined {
    return this.inputs['post_bootstrap_user_data'] as string | undefined;
  }
  public set postBootstrapUserData(value: string | undefined) {
    this.inputs['post_bootstrap_user_data'] = value;
  }
  public get preBootstrapUserData(): string | undefined {
    return this.inputs['pre_bootstrap_user_data'] as string | undefined;
  }
  public set preBootstrapUserData(value: string | undefined) {
    this.inputs['pre_bootstrap_user_data'] = value;
  }
  public get protectFromScaleIn(): boolean | undefined {
    return this.inputs['protect_from_scale_in'] as boolean | undefined;
  }
  public set protectFromScaleIn(value: boolean | undefined) {
    this.inputs['protect_from_scale_in'] = value;
  }
  public get ramDiskId(): string | undefined {
    return this.inputs['ram_disk_id'] as string | undefined;
  }
  public set ramDiskId(value: string | undefined) {
    this.inputs['ram_disk_id'] = value;
  }
  public get schedules(): { [key: string]: any } | undefined {
    return this.inputs['schedules'] as { [key: string]: any } | undefined;
  }
  public set schedules(value: { [key: string]: any } | undefined) {
    this.inputs['schedules'] = value;
  }
  public get securityGroupDescription(): string | undefined {
    return this.inputs['security_group_description'] as string | undefined;
  }
  public set securityGroupDescription(value: string | undefined) {
    this.inputs['security_group_description'] = value;
  }
  public get securityGroupName(): string | undefined {
    return this.inputs['security_group_name'] as string | undefined;
  }
  public set securityGroupName(value: string | undefined) {
    this.inputs['security_group_name'] = value;
  }
  public get securityGroupRules(): any | undefined {
    return this.inputs['security_group_rules'] as any | undefined;
  }
  public set securityGroupRules(value: any | undefined) {
    this.inputs['security_group_rules'] = value;
  }
  public get securityGroupTags(): { [key: string]: string } | undefined {
    return this.inputs['security_group_tags'] as { [key: string]: string } | undefined;
  }
  public set securityGroupTags(value: { [key: string]: string } | undefined) {
    this.inputs['security_group_tags'] = value;
  }
  public get securityGroupUseNamePrefix(): string | undefined {
    return this.inputs['security_group_use_name_prefix'] as string | undefined;
  }
  public set securityGroupUseNamePrefix(value: string | undefined) {
    this.inputs['security_group_use_name_prefix'] = value;
  }
  public get serviceLinkedRoleArn(): string | undefined {
    return this.inputs['service_linked_role_arn'] as string | undefined;
  }
  public set serviceLinkedRoleArn(value: string | undefined) {
    this.inputs['service_linked_role_arn'] = value;
  }
  public get subnetIds(): string[] | undefined {
    return this.inputs['subnet_ids'] as string[] | undefined;
  }
  public set subnetIds(value: string[] | undefined) {
    this.inputs['subnet_ids'] = value;
  }
  public get suspendedProcesses(): string[] | undefined {
    return this.inputs['suspended_processes'] as string[] | undefined;
  }
  public set suspendedProcesses(value: string[] | undefined) {
    this.inputs['suspended_processes'] = value;
  }
  public get tags(): { [key: string]: string } | undefined {
    return this.inputs['tags'] as { [key: string]: string } | undefined;
  }
  public set tags(value: { [key: string]: string } | undefined) {
    this.inputs['tags'] = value;
  }
  public get targetGroupArns(): string[] | undefined {
    return this.inputs['target_group_arns'] as string[] | undefined;
  }
  public set targetGroupArns(value: string[] | undefined) {
    this.inputs['target_group_arns'] = value;
  }
  public get terminationPolicies(): string[] | undefined {
    return this.inputs['termination_policies'] as string[] | undefined;
  }
  public set terminationPolicies(value: string[] | undefined) {
    this.inputs['termination_policies'] = value;
  }
  public get updateLaunchTemplateDefaultVersion(): boolean | undefined {
    return this.inputs['update_launch_template_default_version'] as boolean | undefined;
  }
  public set updateLaunchTemplateDefaultVersion(value: boolean | undefined) {
    this.inputs['update_launch_template_default_version'] = value;
  }
  public get useDefaultTags(): boolean | undefined {
    return this.inputs['use_default_tags'] as boolean | undefined;
  }
  public set useDefaultTags(value: boolean | undefined) {
    this.inputs['use_default_tags'] = value;
  }
  public get useMixedInstancesPolicy(): boolean | undefined {
    return this.inputs['use_mixed_instances_policy'] as boolean | undefined;
  }
  public set useMixedInstancesPolicy(value: boolean | undefined) {
    this.inputs['use_mixed_instances_policy'] = value;
  }
  public get useNamePrefix(): boolean | undefined {
    return this.inputs['use_name_prefix'] as boolean | undefined;
  }
  public set useNamePrefix(value: boolean | undefined) {
    this.inputs['use_name_prefix'] = value;
  }
  public get userDataTemplatePath(): string | undefined {
    return this.inputs['user_data_template_path'] as string | undefined;
  }
  public set userDataTemplatePath(value: string | undefined) {
    this.inputs['user_data_template_path'] = value;
  }
  public get vpcId(): string | undefined {
    return this.inputs['vpc_id'] as string | undefined;
  }
  public set vpcId(value: string | undefined) {
    this.inputs['vpc_id'] = value;
  }
  public get vpcSecurityGroupIds(): string[] | undefined {
    return this.inputs['vpc_security_group_ids'] as string[] | undefined;
  }
  public set vpcSecurityGroupIds(value: string[] | undefined) {
    this.inputs['vpc_security_group_ids'] = value;
  }
  public get waitForCapacityTimeout(): string | undefined {
    return this.inputs['wait_for_capacity_timeout'] as string | undefined;
  }
  public set waitForCapacityTimeout(value: string | undefined) {
    this.inputs['wait_for_capacity_timeout'] = value;
  }
  public get waitForElbCapacity(): number | undefined {
    return this.inputs['wait_for_elb_capacity'] as number | undefined;
  }
  public set waitForElbCapacity(value: number | undefined) {
    this.inputs['wait_for_elb_capacity'] = value;
  }
  public get warmPool(): any | undefined {
    return this.inputs['warm_pool'] as any | undefined;
  }
  public set warmPool(value: any | undefined) {
    this.inputs['warm_pool'] = value;
  }
  public get autoscalingGroupArnOutput() {
    return this.getString('autoscaling_group_arn')
  }
  public get autoscalingGroupAvailabilityZonesOutput() {
    return this.getString('autoscaling_group_availability_zones')
  }
  public get autoscalingGroupDefaultCooldownOutput() {
    return this.getString('autoscaling_group_default_cooldown')
  }
  public get autoscalingGroupDesiredCapacityOutput() {
    return this.getString('autoscaling_group_desired_capacity')
  }
  public get autoscalingGroupHealthCheckGracePeriodOutput() {
    return this.getString('autoscaling_group_health_check_grace_period')
  }
  public get autoscalingGroupHealthCheckTypeOutput() {
    return this.getString('autoscaling_group_health_check_type')
  }
  public get autoscalingGroupIdOutput() {
    return this.getString('autoscaling_group_id')
  }
  public get autoscalingGroupMaxSizeOutput() {
    return this.getString('autoscaling_group_max_size')
  }
  public get autoscalingGroupMinSizeOutput() {
    return this.getString('autoscaling_group_min_size')
  }
  public get autoscalingGroupNameOutput() {
    return this.getString('autoscaling_group_name')
  }
  public get autoscalingGroupScheduleArnsOutput() {
    return this.getString('autoscaling_group_schedule_arns')
  }
  public get autoscalingGroupVpcZoneIdentifierOutput() {
    return this.getString('autoscaling_group_vpc_zone_identifier')
  }
  public get iamInstanceProfileArnOutput() {
    return this.getString('iam_instance_profile_arn')
  }
  public get iamInstanceProfileIdOutput() {
    return this.getString('iam_instance_profile_id')
  }
  public get iamInstanceProfileUniqueOutput() {
    return this.getString('iam_instance_profile_unique')
  }
  public get iamRoleArnOutput() {
    return this.getString('iam_role_arn')
  }
  public get iamRoleNameOutput() {
    return this.getString('iam_role_name')
  }
  public get iamRoleUniqueIdOutput() {
    return this.getString('iam_role_unique_id')
  }
  public get launchTemplateArnOutput() {
    return this.getString('launch_template_arn')
  }
  public get launchTemplateIdOutput() {
    return this.getString('launch_template_id')
  }
  public get launchTemplateLatestVersionOutput() {
    return this.getString('launch_template_latest_version')
  }
  public get platformOutput() {
    return this.getString('platform')
  }
  public get securityGroupArnOutput() {
    return this.getString('security_group_arn')
  }
  public get securityGroupIdOutput() {
    return this.getString('security_group_id')
  }
  protected synthesizeAttributes() {
    return this.inputs;
  }
}
